---
parameters: {}
environment: {}
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: dad-joke
        binary: false
        main: ""
        runtime: python:3.9
        web: false
        webSecure: 
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
